services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
      - "81:81"
      - "8180:8080"
    restart: always
    networks:
      - inception
    volumes:
      - wp-data:/var/www/html:ro
    depends_on:
      - wordpress
      - static_site
      - adminer
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WP_DB_NAME=wordpress
    secrets:
      - wp_db_user
      - wp_db_pass
      - wp_admin_user
      - wp_admin_pass
      - wp_admin_mail
      - wp_user_name
      - wp_user_pass
      - wp_user_mail
      - wp_user_role
    volumes:
      - wp-data:/var/www/html:rw
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    environment:
      - WP_DB_NAME=wordpress
    secrets:
      - wp_db_user
      - wp_db_pass
      - admin_db_user
      - admin_db_pass
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - inception
    restart: always
  # redis: # bonus container
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    environment:
      - NGINX_HOST=${NGINX_HOST:-localhost}
    volumes:
      - wp-data:/home/ftpuser/:rw
    networks:
      - inception
    restart: always
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    depends_on:
      - wordpress
    secrets:
      - ftp_user_pass
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception
  static_site:
    build: ./requirements/bonus/static/
    container_name: portfolio
    networks:
      - inception
    restart: always
    # depends_on:
    #   - nginx
  # service - : bonus

networks:
  inception:
    driver: bridge

volumes:
  db-data:
    driver_opts:
      type: 'none'
      o: bind
      device: ${DATA_PATH}mariadb
  wp-data:
    driver_opts:
      type: 'none'
      o: bind
      device: ${DATA_PATH}wordpress

secrets:
  wp_db_user:
    file: ../secrets/wp_db_user
  wp_db_pass:
    file: ../secrets/wp_db_pass
  admin_db_user:
    file: ../secrets/admin_db_user
  admin_db_pass:
    file: ../secrets/admin_db_pass
  wp_admin_user:
    file: ../secrets/wp_admin_user
  wp_admin_pass:
    file: ../secrets/wp_admin_pass
  wp_admin_mail:
    file: ../secrets/wp_admin_mail
  wp_user_name:
    file: ../secrets/wp_user_name
  wp_user_pass:
    file: ../secrets/wp_user_pass
  wp_user_mail:
    file: ../secrets/wp_user_mail
  wp_user_role:
    file: ../secrets/wp_user_role
  ftp_user_name:
    file: ../secrets/ftp_user_name
  ftp_user_pass:
    file: ../secrets/ftp_user_pass
